/**
 * USER_INFO 회원정보
 */
DROP TABLE USER_INFO;

CREATE TABLE `USER_INFO`
(
	`EMAIL`      VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI NOT NULL COMMENT '이메일',
	`PWD`        VARCHAR(500) COLLATE UTF8MB4_UNICODE_CI NOT NULL COMMENT '비밀번호',
	`NAME`       VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI NOT NULL COMMENT '이름',
	`PHONE`      VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI NOT NULL COMMENT '연락처',
	`SMS_YN`     VARCHAR(1) COLLATE UTF8MB4_UNICODE_CI   NOT NULL DEFAULT 'N' COMMENT 'SMS수신동의여부',
	`EMAIL_YN`   VARCHAR(1) COLLATE UTF8MB4_UNICODE_CI   NOT NULL DEFAULT 'N' COMMENT 'EMAIL수신동의여부',
	`OAUTH_TYPE` VARCHAR(1) COLLATE UTF8MB4_UNICODE_CI COMMENT '소셜로그인구분(G:GOOGLE,N:NAVER,K:KAKAO)',
	`OAUTH_KEY`  VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI COMMENT '소셜로그인KEY',
	`INPUT_DT`   TIMESTAMP                               NOT NULL COMMENT '입력일',
	`INPUT_ID`   VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI NOT NULL COMMENT '입력자',
	`UPDATE_DT`  TIMESTAMP                               NOT NULL COMMENT '수정일',
	`UPDATE_ID`  VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI NOT NULL COMMENT '수정자',
	PRIMARY KEY (`EMAIL`)) ENGINE = InnoDB
						   AUTO_INCREMENT = 8
						   DEFAULT CHARSET = UTF8MB4
						   COLLATE = UTF8MB4_UNICODE_CI COMMENT ='사용자정보'
;

/**
 * PHONE_AUTH_INFO 핸드폰인증
 */
DROP TABLE PHONE_AUTH_INFO;

CREATE TABLE `PHONE_AUTH_INFO`
(
	`SEQ`        INT COLLATE UTF8MB4_UNICODE_CI AUTO_INCREMENT NOT NULL COMMENT 'SEQ',
	`USER_NAME`  VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI       NOT NULL COMMENT '이름',
	`AUTH_NUM`   VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI       NOT NULL COMMENT '인증번호',
	`GROUP_ID`   VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI       NOT NULL COMMENT '[SMS]그룹아이디',
	`MSG_ID`     VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI       NOT NULL COMMENT '[SMS]메세지아이디',
	`ACCOUNT_ID` VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI       NOT NULL COMMENT '[SMS]인증아이디',
	`TO_PHONE`   VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI       NOT NULL COMMENT '[SMS]핸드폰번호',
	`STAT_CODE`  VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI       NOT NULL COMMENT '[SMS]상태코드',
	`STAT_MSG`   VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI       NOT NULL COMMENT '[SMS]상태메세지',
	`COUNTRY`    VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI       NOT NULL COMMENT '[SMS]국가코드',
	`INPUT_DT`   TIMESTAMP                                     NOT NULL COMMENT '입력일',
	`INPUT_ID`   VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI       NOT NULL COMMENT '입력자',
	PRIMARY KEY (`SEQ`)) ENGINE = InnoDB
						 AUTO_INCREMENT = 8
						 DEFAULT CHARSET = UTF8MB4
						 COLLATE = UTF8MB4_UNICODE_CI COMMENT ='휴대폰인증정보'

/**
 * EDT_MSG_INFO EDITOR MESSAGE 저장
 */
DROP TABLE EDT_MSG_INFO;

CREATE TABLE EDT_MSG_INFO
(
	SEQ           INT AUTO_INCREMENT COMMENT 'SEQ' PRIMARY KEY,
	EDT_ID        VARCHAR(100)                                NOT NULL COMMENT 'EDITOR 아이디',
	EDT_TITLE     VARCHAR(4000)                               NOT NULL COMMENT '제목',
	EDT_SUB_TITLE VARCHAR(4000) DEFAULT '소제목'                 NULL,
	EDT_TEXT      VARCHAR(4000)                               NOT NULL COMMENT '내용',
	MAIN_IMG_PATH VARCHAR(400)  DEFAULT '대표이미지경로'             NULL,
	VIEW_CNT      INT           DEFAULT 0                     NULL COMMENT '조회수',
	PAGE          VARCHAR(200)                                NOT NULL COMMENT '페이지',
	QNA_PASSWORD  VARCHAR(100)                                NULL COMMENT '비밀글 비밀번호',
	QNA_SECURE_YN VARCHAR(1)    DEFAULT 'N'                   NULL COMMENT '비밀글 여부',
	DEL_YN        VARCHAR(1)    DEFAULT 'N'                   NULL COMMENT '삭제여부',
	INPUT_ID      VARCHAR(100)                                NOT NULL COMMENT '입력자',
	INPUT_NAME    VARCHAR(100)                                NULL COMMENT '등록자 이름',
	INPUT_DT      TIMESTAMP                                   NOT NULL COMMENT '입력일',
	UPDATE_ID     VARCHAR(100)                                NOT NULL COMMENT '수정자',
	UPDATE_NAME   VARCHAR(100)                                NULL COMMENT '수정자 이름',
	UPDATE_DT     TIMESTAMP                                   NOT NULL COMMENT '수정일')
	COMMENT '게시판메시지' COLLATE = UTF8MB4_UNICODE_CI;


/**
 * EMAIL_CERT_INFO 이메일 인증
 */
DROP TABLE EMAIL_CERT_INFO;

CREATE TABLE `EMAIL_CERT_INFO`
(
	`SEQ`        INT COLLATE UTF8MB4_UNICODE_CI AUTO_INCREMENT NOT NULL COMMENT 'SEQ',
	`SESSION_ID` VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI       NOT NULL COMMENT '세션ID',
	`EMAIL`      VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI       NOT NULL COMMENT '이메일',
	`CERT_NUM`   VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI       NOT NULL COMMENT '인증번호',
	`PAGE`       VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI       NOT NULL COMMENT '화면구분',
	`CERT_YN`    VARCHAR(1) DEFAULT 'N' COMMENT '인증완료여부',
	`INPUT_DT`   TIMESTAMP                                     NOT NULL COMMENT '입력일',
	`INPUT_ID`   VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI       NOT NULL COMMENT '입력자',
	PRIMARY KEY (`SEQ`)) ENGINE = InnoDB
						 AUTO_INCREMENT = 8
						 DEFAULT CHARSET = UTF8MB4
						 COLLATE = UTF8MB4_UNICODE_CI COMMENT ='이메일인증정보'
	;


/**
 * ERR_LOG 저장
 */
DROP TABLE ERR_LOG;

CREATE TABLE `ERR_LOG`
(
	`SEQ`      INT COLLATE UTF8MB4_UNICODE_CI AUTO_INCREMENT NOT NULL COMMENT 'SEQ',
	`ERR_CODE` VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI       NOT NULL COMMENT '에러코드',
	`ERR_MSG`  VARCHAR(4000) COLLATE UTF8MB4_UNICODE_CI       NOT NULL COMMENT '에러메시지',
	`USER_IP`  VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI       NOT NULL COMMENT '사용자IP',
	`INPUT_DT` TIMESTAMP                                     NOT NULL COMMENT '입력일',
	`INPUT_ID` VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI       NOT NULL COMMENT '입력자',
	PRIMARY KEY (`SEQ`)) ENGINE = InnoDB
						 AUTO_INCREMENT = 8
						 DEFAULT CHARSET = UTF8MB4
						 COLLATE = UTF8MB4_UNICODE_CI COMMENT ='에러로그'
;
/**
 * 파일 저장
 */
DROP TABLE FILE_INFO;
CREATE TABLE `FILE_INFO`
(
	`SEQ`            INT COLLATE UTF8MB4_UNICODE_CI AUTO_INCREMENT NOT NULL COMMENT '파일번호(PK)',
	`EDT_SEQ`        BIGINT(20)                                    NOT NULL COLLATE UTF8MB4_UNICODE_CI COMMENT '게시글 번호 (FK)',
	`ORG_FILE_NAME`  VARCHAR(255)                                  NOT NULL COLLATE UTF8MB4_UNICODE_CI COMMENT '원본 파일명',
	`SAVE_FILE_NAME` VARCHAR(40)                                   NOT NULL COLLATE UTF8MB4_UNICODE_CI COMMENT '저장 파일명',
	`FILE_SIZE`      INT(11)                                       NOT NULL COLLATE UTF8MB4_UNICODE_CI COMMENT '파일 크기',
	`INPUT_DT`       TIMESTAMP                                     NOT NULL COMMENT '생성일시',
	`INPUT_ID`       VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI       NOT NULL COMMENT '입력자',
	PRIMARY KEY (`SEQ`)) COMMENT '파일 저장';

/**
 * BOARD_COMMENT 게시판 댓글
 */
DROP TABLE BOARD_COMMENT;
CREATE TABLE BOARD_COMMENT
(
	COMMENT_SEQ INT AUTO_INCREMENT PRIMARY KEY,
	EDT_SEQ     INT                             COLLATE UTF8MB4_UNICODE_CI      NOT NULL COMMENT '게시판 시퀀스',
	COMMENT_DEPTH VARCHAR(1000)                 COLLATE UTF8MB4_UNICODE_CI      NULL COMMENT '댓글DEPTH',
	COMMENT_TEXT     VARCHAR(2000)                   COLLATE UTF8MB4_UNICODE_CI      NULL COMMENT '댓글내용',
	COMMENT_PASSWORD    VARCHAR(100)                    COLLATE UTF8MB4_UNICODE_CI      NULL COMMENT '댓글비밀번호',
	SECURE_YN   VARCHAR(1)                      COLLATE UTF8MB4_UNICODE_CI      NULL COMMENT '비밀댓글여부',
	DEL_YN        VARCHAR(1)    DEFAULT 'N'                   NULL COMMENT '삭제여부',
	IMG_PATH    VARCHAR(1000)            COLLATE UTF8MB4_UNICODE_CI        NULL COMMENT '이미지경로',
	INPUT_ID    VARCHAR(100)                 COLLATE UTF8MB4_UNICODE_CI        NULL COMMENT '등록자아이디',
	INPUT_NAME  VARCHAR(100)                 COLLATE UTF8MB4_UNICODE_CI        NULL COMMENT '등록자 이름',
	INPUT_DT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록일시',
	UPDATE_ID   VARCHAR(100)                 COLLATE UTF8MB4_UNICODE_CI         NULL COMMENT '수정자 아이디',
	UPDATE_NAME VARCHAR(100)                 COLLATE UTF8MB4_UNICODE_CI         NULL COMMENT '수정자 이름',
	UPDATE_DT   TIMESTAMP                           NULL COMMENT '수정일시')
	COMMENT '게시판댓글';


/**
 * 후원 정보
 */
DROP TABLE DONATE_INFO;
CREATE TABLE DONATE_INFO
(
	DONATE_SEQ INT AUTO_INCREMENT PRIMARY KEY,
	ENC_DONATE_SEQ     VARCHAR(200) COLLATE UTF8MB4_UNICODE_CI NOT NULL COMMENT '후원시퀀스(암호화)',
	USER_ID     VARCHAR(100) COLLATE UTF8MB4_UNICODE_CI NOT NULL COMMENT '유저이메일',
	REQ_NAME     VARCHAR(100)  COLLATE UTF8MB4_UNICODE_CI                     NULL COMMENT '신청자명',
	REQ_PHONE   VARCHAR(100)   COLLATE UTF8MB4_UNICODE_CI                    NULL COMMENT '신청자연락처',
	REQ_EMAIL   VARCHAR(100)   COLLATE UTF8MB4_UNICODE_CI                    NULL COMMENT '신청자이메일',
	DONATE_AMOUNT NUMERIC       COLLATE UTF8MB4_UNICODE_CI                    NULL COMMENT '후원금액',
	DONATE_SURVEY_01    VARCHAR(4)          COLLATE UTF8MB4_UNICODE_CI              NULL COMMENT '후원설문1',
	DONATE_SURVEY_TEXT_01    VARCHAR(2000)  COLLATE UTF8MB4_UNICODE_CI                      NULL COMMENT '후원설문1',
	DONATE_SURVEY_02   VARCHAR(4)           COLLATE UTF8MB4_UNICODE_CI               NULL COMMENT '후원설문2',
	DONATE_SURVEY_TEXT_02   VARCHAR(2000)   COLLATE UTF8MB4_UNICODE_CI                       NULL COMMENT '후원설문2',
	RESI_NUM           VARCHAR(200)    COLLATE UTF8MB4_UNICODE_CI                      NULL COMMENT '기부금영수증용-주민등록번호',
	INPUT_ID    VARCHAR(100)      COLLATE UTF8MB4_UNICODE_CI                  NULL COMMENT '등록자아이디',
	INPUT_NAME  VARCHAR(100)      COLLATE UTF8MB4_UNICODE_CI                  NULL COMMENT '등록자 이름',
	INPUT_DT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록일시')
	COMMENT '후원정보';
)
