-- =========================================================
-- JARAM COMMENTS TABLE
-- 문의게시판(qna) 단일 댓글용
-- =========================================================

create table if not exists jaram.comments (
  id bigint generated by default as identity primary key,

  post_id bigint not null references jaram.posts(id) on delete cascade,

  content text not null,
  is_private boolean not null default false,
  is_deleted boolean not null default false,

  author_id text not null,
  author_name text not null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table jaram.comments is '게시글 댓글';
comment on column jaram.comments.post_id is '게시글 ID';
comment on column jaram.comments.content is '댓글 내용';
comment on column jaram.comments.is_private is '비밀댓글 여부';
comment on column jaram.comments.is_deleted is '삭제 여부';
comment on column jaram.comments.author_id is '작성자 사용자 ID';
comment on column jaram.comments.author_name is '작성자 이름';
comment on column jaram.comments.created_at is '생성일시';
comment on column jaram.comments.updated_at is '수정일시';

create index if not exists comments_post_id_created_at_idx
  on jaram.comments (post_id, created_at);

create index if not exists comments_author_id_idx
  on jaram.comments (author_id);

grant select, insert, update, delete on jaram.comments to service_role;
grant usage, select on sequence jaram.comments_id_seq to service_role;
