-- =========================================================
-- JARAM SUPABASE DATABASE SQL
-- schema: jaram
-- description:
--   - 자람 사이트용 기본 테이블/권한/RLS 정의
--   - 현재 posts 테이블만 RLS 적용
--   - legacy_users 는 마이그레이션 보관용
--   - file_info 는 첨부파일 메타 정보용
-- =========================================================


-- =========================================================
-- 1. SCHEMA
-- =========================================================

create schema if not exists jaram;


-- =========================================================
-- 2. TABLES
-- =========================================================

-- -----------------------------------------
-- 2.1 posts
-- 설명:
--   - 공지사항, 뉴스, 갤러리, qna 등 게시글 공통 테이블
--   - legacy EDT_MSG_INFO 이관 대상
-- -----------------------------------------
create table if not exists jaram.posts (
  id bigint generated by default as identity primary key,

  title text not null,
  sub_title text,
  content text not null,

  main_image_url text,
  view_count integer default 0,

  page text not null,

  is_private boolean default false,
  password text,

  is_deleted boolean default false,

  author_id text,
  author_name text,

  created_at timestamptz default now(),
  updated_at timestamptz default now()
);


comment on table jaram.posts is '게시글 공통 테이블';
comment on column jaram.posts.title is '제목';
comment on column jaram.posts.sub_title is '소제목';
comment on column jaram.posts.content is '본문 HTML';
comment on column jaram.posts.main_image_url is '대표 이미지 URL';
comment on column jaram.posts.view_count is '조회수';
comment on column jaram.posts.page is '게시판 구분(notice, news, gallery, qna, ceo 등)';
comment on column jaram.posts.is_private is '비밀글 여부';
comment on column jaram.posts.password is '비밀글 비밀번호 또는 해시';
comment on column jaram.posts.is_deleted is '삭제 여부';
comment on column jaram.posts.author_id is '작성자 ID 또는 이메일';
comment on column jaram.posts.author_name is '작성자 이름';
comment on column jaram.posts.created_at is '생성일시';
comment on column jaram.posts.updated_at is '수정일시';


-- -----------------------------------------
-- 2.2 file_info
-- 설명:
--   - 게시글/댓글 첨부파일 메타 정보
--   - 실제 파일은 추후 Supabase Storage 사용 예정
-- -----------------------------------------
create table if not exists jaram.file_info (
  id bigint generated by default as identity primary key,

  post_id bigint,
  comment_id bigint,

  original_file_name text not null,
  stored_file_name text not null,

  file_size bigint not null,

  created_at timestamptz default now(),
  created_by text
);


comment on table jaram.file_info is '첨부파일 메타 정보';
comment on column jaram.file_info.post_id is '게시글 ID';
comment on column jaram.file_info.comment_id is '댓글 ID';
comment on column jaram.file_info.original_file_name is '원본 파일명';
comment on column jaram.file_info.stored_file_name is '저장 파일명';
comment on column jaram.file_info.file_size is '파일 크기(byte)';
comment on column jaram.file_info.created_at is '생성일시';
comment on column jaram.file_info.created_by is '등록자';

-- Storage 경로 규칙:
-- - stored_file_name 에 폴더가 없으면 created_at 기준 uploadfile/YYMMDD 폴더를 붙인다.
-- - 예: created_at = 2026-04-23, stored_file_name = abc.pdf -> attachment/uploadfile/260423/abc.pdf
-- - stored_file_name 에 날짜 폴더가 포함되어 있으면 uploadfile 을 앞에 붙여 사용한다.
-- - stored_file_name 이 이미 uploadfile/ 로 시작하면 해당 경로를 그대로 사용한다.



-- -----------------------------------------
-- 2.3 legacy_users
-- 설명:
--   - 기존 USER_INFO 이관 보관용
--   - 운영 인증은 추후 Supabase Auth + profiles 권장
--   - 프론트 직접 노출 금지
-- -----------------------------------------
create table if not exists jaram.legacy_users (
  email text primary key,
  password text not null,

  user_name text not null,
  phone text not null,

  sms_agree boolean default false,
  email_agree boolean default false,

  oauth_type text,
  oauth_key text,

  created_at date,
  created_by text,

  updated_at date,
  updated_by text
);


comment on table jaram.legacy_users is '기존 회원 정보 이관 보관용 테이블';
comment on column jaram.legacy_users.email is '이메일(PK)';
comment on column jaram.legacy_users.password is '기존 비밀번호 또는 해시';
comment on column jaram.legacy_users.user_name is '이름';
comment on column jaram.legacy_users.phone is '연락처';
comment on column jaram.legacy_users.sms_agree is 'SMS 수신 동의';
comment on column jaram.legacy_users.email_agree is '이메일 수신 동의';
comment on column jaram.legacy_users.oauth_type is '소셜 로그인 구분';
comment on column jaram.legacy_users.oauth_key is '소셜 로그인 키';
comment on column jaram.legacy_users.created_at is '등록일';
comment on column jaram.legacy_users.updated_at is '수정일';


-- =========================================================
-- 3. INDEXES
-- =========================================================

create index if not exists idx_posts_page on jaram.posts(page);
create index if not exists idx_posts_created_at on jaram.posts(created_at desc);
create index if not exists idx_posts_is_deleted on jaram.posts(is_deleted);
create index if not exists idx_posts_is_private on jaram.posts(is_private);

create index if not exists idx_file_info_post_id on jaram.file_info(post_id);


-- =========================================================
-- 4. GRANTS
-- 설명:
--   - jaram 스키마 사용 권한
--   - posts: 프론트 공개 조회를 위해 anon/authenticated select만 허용
--   - file_info: 공개 게시글에 연결된 첨부파일 메타만 select 허용
--   - legacy_users: 프론트 직접 접근 금지
-- =========================================================

grant usage on schema jaram to anon, authenticated, service_role;

revoke all on jaram.posts from anon, authenticated;
grant select on jaram.posts to anon, authenticated;
grant select, insert, update, delete on jaram.posts to service_role;

revoke all on jaram.file_info from anon, authenticated;
grant select on jaram.file_info to anon, authenticated;
grant select, insert, update, delete on jaram.file_info to service_role;

-- legacy_users 는 프론트 직접 접근 금지 권장
revoke all on jaram.legacy_users from anon, authenticated;


-- =========================================================
-- 5. RLS
-- 설명:
--   - 현재 posts만 RLS 설정
--   - 삭제되지 않았고 비밀글이 아닌 게시글만 공개 조회 가능
-- =========================================================

alter table jaram.posts enable row level security;
alter table jaram.posts force row level security;

alter table jaram.file_info enable row level security;
alter table jaram.file_info force row level security;

alter table jaram.legacy_users enable row level security;
alter table jaram.legacy_users force row level security;

drop policy if exists "public read visible posts" on jaram.posts;

create policy "public read visible posts"
on jaram.posts
for select
to anon, authenticated
using (
  is_deleted = false
  and is_private = false
);

drop policy if exists "deny file info direct access" on jaram.file_info;
drop policy if exists "deny legacy users direct access" on jaram.legacy_users;
drop policy if exists "public read visible post files" on jaram.file_info;

create policy "public read visible post files"
on jaram.file_info
for select
to anon, authenticated
using (
  exists (
    select 1
    from jaram.posts
    where posts.id = file_info.post_id
      and posts.is_deleted = false
      and posts.is_private = false
  )
);


-- =========================================================
-- 6. OPTIONAL / FUTURE NOTES
-- =========================================================

-- [중요]
-- 1) Supabase Dashboard > API 설정에서 exposed schema 에 jaram 추가 필요
-- 2) exposed tables 에서 posts, file_info 만 우선 노출 권장
-- 3) legacy_users 는 exposed tables 에 포함하지 않는 것을 권장
-- 4) file_info 는 공개 게시글 첨부파일 메타 조회에만 사용
-- 5) 운영용 관리자 등록/수정/삭제 정책은 추후 auth 기반으로 별도 추가 권장


-- =========================================================
-- 7. STORAGE POLICY (NOT APPLIED YET)
-- 설명:
--   - 아직 미적용
--   - editor-images, attachment 버킷 정책은 security-policies.sql 참고
-- =========================================================

-- 예시 메모:
-- - editor-images: 공개 조회 가능 / 관리자만 업로드
-- - attachment: 공개 게시글 첨부파일 다운로드용
